### ISSUE TITLE
Implement option to reverse relay positions

### ISSUE THREAD

**Issue by tpanajott** [NSPManager/NSPanelManager#62]
Implement option for the user to "switch place" of the relays. This is especially useful if the user has installed it with the wires the wrong way around.

**Comment by gvitzi** [comment]
If you mean that button-1 will control relay-2 and vice-versa, Then I just wanted to note that this can be achieved already (at least with Home-Assistant) since the relays are reported as switches in HA, They can be added as lights in the room and then selected in the "Detached Mode" in a reverse manner.

**Comment by tpanajott** [comment]
> If you mean that button-1 will control relay-2 and vice-versa, Then I just wanted to note that this can be achieved already (at least with Home-Assistant) since the relays are reported as switches in HA, They can be added as lights in the room and then selected in the "Detached Mode" in a reverse manner.

Yes, this is what I meant :) Good workaround!

**Comment by tpanajott** [comment]
Functionality added in latest merge, closing.
